#!/bin/bash

RHELV=$(facter operatingsystemmajrelease)
# Parameter 1 is name of service to control
if [ $RHELV -gt 6 ]; then
    if [ -f /etc/init.d/$1 ]; then
        /etc/init.d/$1 status        # For RHEL6
    else
        /usr/bin/systemctl status $1 # For RHEL7
    fi
else
    /etc/init.d/$1 status        # For RHEL6
fi
if (( $? == 0 )); then
    exit 110 # the resource is online with 100 percent confidence
else
    exit 100 # the resource is offline
fi
